  katelyn/DonorsPageUI[m
  main[m
* [32msweekrit-about-us-page-ui[m
  sweekrit-client-story-component[m
  sweekrit-contact-request-backend-route[m
  sweekrit-how-can-you-help-scroll[m
  sweekrit-privacy-policy-page[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/carousel-implementation[m
  [31mremotes/origin/donors/clients/members-implementation[m
  [31mremotes/origin/highlight-routes[m
  [31mremotes/origin/jjescobedo/ContactUsUI[m
  [31mremotes/origin/jjescobedo/FooterContactRouting[m
  [31mremotes/origin/jjescobedo/HomePage[m
  [31mremotes/origin/jjescobedo/HomePageUI[m
  [31mremotes/origin/jjescobedo/ImpactMetricsBackendRoutes[m
  [31mremotes/origin/jjescobedo/MeetTheTeamPageUI[m
  [31mremotes/origin/jjescobedo/MembersPageUI[m
  [31mremotes/origin/jjescobedo/TeamMembersUIandAPI[m
  [31mremotes/origin/jjescobedo/TermsAndConditionsPage[m
  [31mremotes/origin/jjescobedo/UpdateMembersPUT[m
  [31mremotes/origin/jjescobedo/WorldMap[m
  [31mremotes/origin/katelyn/ClientsPUTRoute[m
  [31mremotes/origin/katelyn/ClientsWeveSupportedComponent[m
  [31mremotes/origin/katelyn/DonorsPageUI[m
  [31mremotes/origin/katelyn/FooterRouting[m
  [31mremotes/origin/katelyn/UpdateImpactMetricsComponent[m
  [31mremotes/origin/main[m
  [31mremotes/origin/members-page-components[m
  [31mremotes/origin/mongo-setup[m
  [31mremotes/origin/munachio/clientHighlights[m
  [31mremotes/origin/munachio/clientHighlightsTailwind[m
  [31mremotes/origin/munachio/clients-page-ui[m
  [31mremotes/origin/services-we-offer-component-suhaan[m
  [31mremotes/origin/sweekrit-about-us-page-ui[m
  [31mremotes/origin/sweekrit-client-story-component[m
  [31mremotes/origin/sweekrit-contact-request-backend-route[m
  [31mremotes/origin/sweekrit-how-can-you-help-scroll[m
  [31mremotes/origin/sweekrit-privacy-policy-page[m
  [31mremotes/origin/timeline-component[m
  [31mremotes/origin/tony/MinorHomePageDesignFixes[m
  [31mremotes/origin/westonz7042/firebase-backend-auth-setup[m
  [31mremotes/origin/yasmin/navbar[m
  [31mremotes/origin/yasmin/studyscrollingcomp[m
  [31mremotes/origin/yasmink/navbar[m
